apiVersion: v1
kind: Secret
metadata:
    name: recyclarr
    namespace: apps
type: Opaque
stringData:
    SONARR_API_KEY: ENC[AES256_GCM,data:2J5NqvrWxKAsb8NhBHgVOP1LPL7s3uHT79eFOziw7FY=,iv:Mi/EFjweWnWudhqvCn3NYBID3Cn2C0mPg6/xKoLpkQk=,tag:KB/ifFXzz5BT/i03bt8Njg==,type:str]
    RADARR_API_KEY: ENC[AES256_GCM,data:kY9YXpFtyIs/8KLtbifa1NRW7vrmItDOQW+ltDOe3kE=,iv:w8c+2B22jmu33MtIMToWaY/b5eN7QkF0KkmW8mBtIx8=,tag:zk7zJ99hPoOdi+lWqrbpAQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h440ezlz0n2wf57mvdzfes8hglf7p543ryggjwgywlwlrwlmhczs4qtdzz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPVmFnNG5RTTVyNUphWVM5
            OExYeXRGbE1zYXJMUTBvenJwelJtT3VXNmx3Cktkd3p0OUxlTlZBTitEdER1TkxD
            a1gzUjdZbFQ4QksvTU5jZDVQOU9vN00KLS0tIGlFWVlHUk1MTFpDWDJKSkkvTDBR
            T2Q1WXVVRFUzMWdGejNzZTJTTTd5RzQKca5zCxO+f5JEWtcuGayDIpDxhDtayHqp
            grYXJSD569NnchZuN1nlYgXlzv3BWE9Posx6b91gJqRsJXQgJ9jr0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-10T15:55:38Z"
    mac: ENC[AES256_GCM,data:UIBbOksqkR2Sm2ZZ6XSMJvw60mw1hGf4RcpA2WdujNi5bumag5q8xT3UgpETiEtUgYqtQFdRRsIbfAAwRtDhgMq438NmNVNyzsAou3Ui28kcg+w98QH8b328EfNsgonUKIy+Jya4c4MAkBIO0Ugp/qNl4V1EIT8pe5excvQnx6Q=,iv:K2uLxKorZkLmdS+WtBNXqI4RhhPVxTcGMIY4Xt6h7/s=,tag:6QgY4JFwBYXbx2IiyvSuIw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
