apiVersion: v1
kind: Secret
metadata:
    name: recyclarr
    namespace: apps
type: Opaque
stringData:
    SONARR_API_KEY: ENC[AES256_GCM,data:91zXYYB4NBuA/0Cb+zD2gQPsv9iVuXj5xbbPFzSEDvg=,iv:FGYPZ+lb0/m/I67pC5PJUFLBbjDlj6OA4ZJZDybwgPM=,tag:X0Cf/pjmJjVG0hvTh4GZBw==,type:str]
    RADARR_API_KEY: ENC[AES256_GCM,data:BL/j1tP877m19TSWBRWFvSfc0NaX4b0zbO0isrSir9k=,iv:zMkOiYfJhHV3kizXfbrfCPzVShozl/Eo1F2mS03RZ2Y=,tag:D4ongA7sIjlRtQVBqvV+eQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h440ezlz0n2wf57mvdzfes8hglf7p543ryggjwgywlwlrwlmhczs4qtdzz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0clJGRWRlS2Frc0NadDB0
            QVpPeTNyTWNRV1FzZ0FldkdBZXN6R0R4OG5nClhVS1Y5dFl2b0tOR1RObFd6bVEy
            akVDR1FadWtiVXhNKzk1YUVkc1dYRXMKLS0tIDVQVXJ3a01kcjFjVXF2YWpSMEZ0
            d1pzY0x2dUludHNDRENIM0M2S1lQSDQKfUUe8ZbIyKWp/HySx8EnHH788y9FQFiL
            33zvqEOB3oNZNPnJiO3Yc0UD8t9gEsY8XgcbMIJdfnP4+DvrKCEbYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T16:44:24Z"
    mac: ENC[AES256_GCM,data:JhKjDB0S+QU0e8v5kVBUq0s1SjvNALzk1+PygYU66nbn4EbpP43cCcLBbNZwq+Dn/Y8FaL7IqDlbe1UvzHypMdgCxi9tAe90jW9pfXmugmlbGuZLRfDwN16YpwWSoY8CXJPYl7GTK89MLQqkL54ajNSx1i9kvc+mahj7CRTsLlY=,iv:yzn20i1vRDTaisvD4p4bmNFxHpQbAjZ3aNtAIKYdiAU=,tag:h4k29lRMRJ0vtfGsu+F6Fw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
