apiVersion: v1
kind: ConfigMap
metadata:
    name: orchard-bot-config
    namespace: apps
data:
    config.toml: ENC[AES256_GCM,data:wsAs27oK1Nmgmw8BXyk338KEuzWGV0N3EE2n/b32pvciKGwrNZqcu2XzfWvfX0vH2Tt+2rciIGqnHbyx4b0L3THE6e1LiUiBNNS8sGMyPWkDer/mVpXc1GUe+k31cIok9HH16g9gNFIOPHVE/KDrykfpRdTYPkWQNalYF7kMyPQ0AwQZPGBFDF15qQTIrynz2g/A1gaQybEnWxGVZoZZOL0/9cJvmNGD/980klhvlovrGh9OThohfdibLI/JdPdyJzmD9mTH63Q2NsUB3ivTiuyI1ArLnQlbBTpzw5bybb+4FGqhu8JTVjJAlS0iMNWAayMb2ecK84VmBELcJWq+ivyDSBQ6FFl4yBFBkqDTEu1sMO2QCOYA8Uoz4EULC/96clwINkmBiGnkhQglxFIHGl0w7Dzrfik5ZESYIxSKlXFztP7oeHzQ1Ic63rNQ1HmN3rNFWBU7CtVGQSvmTyDAUsdFEzfSPI7MZWplyRKDRaJpDZxVaF2WpTnlyg1Ja4c7AX33bfIIlRFEiCRQbVND0p6jbhRf5fBj4S+ycuQmD6k/ZkV48xLpNNOpGFJJOUlgacvJq39Cx/QH3lIEqLaVnPf8yQvQXB79ZzJkc3QsgG3A1LXJlH/xdR8SQMHkwg5qdA+m33ezT0ODIANXc+G97npYI+4q3YG6iZG0NZnIE1J+v1Q8NlACDajzZyjWqkOfInVvjNHy+GXV+ieBdx4N0VEdnoE7UgzGtTJKcmGyoJXA0uJHM0gEUNXueTmUxqWfTsOVW72YsV/2eqjdFtU4FboHvDog35zsjR56WRIHMZoTluWJAQgHgrHStQl2+OJTE42cxfQjHswdbkCNM9MzJuWbe3Sf+b2p7r/6zIkQgdEM57NhpN8uI3meqw/mv9PVT7hBwrAIPuqGhc6ZPhmVo9zXX/BB8pQNLZmBkKsHnuTC+ex4UeA6LPkUbMD5DdbcjuwA+sl1,iv:XcXdbK5Q8a0cDcLDYO2FHOe5zvHz0+eZPVwA1R9Kjxc=,tag:tpYPoXvLeoRWs+5WkCZ6AQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h440ezlz0n2wf57mvdzfes8hglf7p543ryggjwgywlwlrwlmhczs4qtdzz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3eHFlekFaWCsyTEF3ZGNy
            ZjdPVHFJK1Yzek5JUTR3MVkvZEk2M1gxSVM4CnlzUWVESkdjNnRzL0VXTVZNTXY3
            b1JoMjdMZW93c3pZSm1YMElNZ3VMalEKLS0tIERXVEhOMkhaK0tOV08zdVhyZ1Nl
            MVRUZUlWZ3cxdU1JZnhDUEpZZlYxKzQKG4ATDuGOfgb5eaOXA9JUb6Xozr3qb2FQ
            K5WiuDGqRGIbBaw0ze51XXaFlCQSFN4ulMHMnHtJSxrcINfsVGdqjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-19T18:56:18Z"
    mac: ENC[AES256_GCM,data:rT0dSSvcSlr7TL21DOolD6w7g1aQEcQtp4U7g0K6AFmgqU0qxWAJWjxTG0DoRkyZgzW49ndGJoOIJodD6npcn2xA2jyMFdy35LTkA29EJFlS835jtkWa5mDue844iy8McrSSlrHh7ClM43VJxvocY8ngJ+OkkvT7vTe6gc8f/s4=,iv:bXrLu2rZKVDCpWtmMa63KrCZQAtoy1UuVL7dbTqgx54=,tag:UoqpzZ61qH2ik+i6VohZaA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
