apiVersion: v1
kind: ConfigMap
metadata:
  name: orchard-bot-config
  namespace: apps
data:
  config.toml: |
    [discord]
    token = "${DISCORD_TOKEN}"

    [db]
    host = "postgres.infra.svc.cluster.local"
    port = 5432
    db = "orchard"
    username = "postgres"
    password = "${DB_PASSWORD}"

    [ai]
    key = "${AI_KEY}"
    base_url = "https://openrouter.ai/api/v1/v1"
    model = "google/gemini-2.0-flash-001"

    [minecraft]
    rcon_host = "192.168.0.25"
    rcon_port = 25575
    rcon_password = "${RCON_PASSWORD}"
    smp_role = "1332496030935023649"

    [amqp]
    url = "amqp://guest:guest@rabbitmq.infra.svc.cluster.local:5672/"

    [modules.apps]
    app_log = "1332791738292637736"

    [modules.chat]
    chat_channel = "1336812976782704743"
    linked_role = "1337185483620618291"
