apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchard-bot
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orchard-bot
  template:
    metadata:
      labels:
        app: orchard-bot
    spec:
      containers:
        - name: orchard-bot
          image: ghcr.io/jenyaftw/orchard-bot:latest
          volumeMounts:
            - name: config-map
              mountPath: /config.toml
              subPath: config.toml
          command: ["/orchard-bot"]
      imagePullSecrets:
        - name: ghcr-jenyaftw
      volumes:
        - name: config-map
          configMap:
            name: orchard-bot-config
