apiVersion: v1
kind: Secret
metadata:
    name: orchard-bot-secret
stringData:
    DISCORD_TOKEN: ENC[AES256_GCM,data:SD5NQPhTGgWD43+TXD46C9ioRgWryO+7cnOPiH6hrE8IU875tUuhQ8Ak7d4megkFNBNVXXgIzVKh2tLDtpqX9rHNaPb2jDbi,iv:JAPavr0ALMZ9cSvHeDoUhXkRgef1U/SGyzvcQ9NbcjM=,tag:SUaRUgjPGuvVYrANGTAvlQ==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:R+hHMA4+p0K56uEG,iv:m9dJfKiWDqH0iUDFy6tHo7nCS+yZvUz7Ly5KLmIg/DY=,tag:EviMofCbnjkFp8Uyr7bu8w==,type:str]
    AI_KEY: ENC[AES256_GCM,data:2JJEwOT5uUy1rnBbMYafgDFZG/L1tuKbr6jf4Ehhe1L6lvbLYHFZm0gVn1AHBy4Pov6dFNa3ZJaoGciMWKbwXPZTKN6PiRZzgw==,iv:iyxWnYMfUeLS8lnHkRaryVamByD9lHU3svgvrGmDPqs=,tag:XTU4IO90aGnANf921XiDhQ==,type:str]
    RCON_PASSWORD: ENC[AES256_GCM,data:9GR3W30WlrDEs3EMk/VqA8hN,iv:CVkomNYvcmnqGG8jf1jiWx1y9UtPVka1LPqT15+aITE=,tag:NWNGT1VrD9+6mUvDbQH/aA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h440ezlz0n2wf57mvdzfes8hglf7p543ryggjwgywlwlrwlmhczs4qtdzz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2N1ZuTklQMm96QmJMcFpW
            NzNPaGRSNC81eFFYTGR3Sy9LNW9iaWxSUmgwClFjZEhBWEt5MnhrL0w0eFMvamMr
            WkJ0KzhGUEJNeEh0ZDQyS1gyR2ZrZ2MKLS0tIEkwWXZXM0tFRG0xbVhBUUFCMXJ4
            VUxPR1cwWUN1a250d2RWS1FydFpNNnMKMmemkMoN3sgs2h0tRt1lKdReTJNs91o1
            +8fJJncae5/ulav0MZjbNLPjg81fC8qRZy7cqwkoK4p3GyixCK5KLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-19T17:04:41Z"
    mac: ENC[AES256_GCM,data:m4Lsp4DryHPxpjbIBVEvE44vYw6ELYaWCs/vnrMusNrQ4A2s7ARr6T7e9NzOEqU2MJHebFUMObuCWC0ct2hSix/2wgJD8jZMiS2qCoNHXlsmYGIgga4YsURSusb3cdWnIkvcV4/xKHCBtnafsKYwtNIzeBB7AuSmZy1eiHPONuo=,iv:3d6WFzkyXBAj88T/oSwI1mUTBMEmLcCydzXL0vn1V80=,tag:UqYyqfsxwKcTcgG4f8GHPA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
