apiVersion: v1
kind: Secret
metadata:
    name: orchard-bot-secret
    namespace: apps
stringData:
    DISCORD_TOKEN: ENC[AES256_GCM,data:dVGvbjgHaFMeOLdbHrunePiSWGLH3FiZBWKNA2jomVJDRrYSCVwa16L2X+IhuU95MDRtS+LuX3aiVNc3vOP9ia84Iy8PRGC0,iv:0ufmEo1Z7Tz8DLsMwHVsKDQ7K1hCM8UPs5XAeAN8aKM=,tag:Fpt8Cr/25F/U693C6gU1OQ==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:kp5WWskeXMjkjQ0+,iv:ouyQbTrwca6dINcWcDyWh1cAVj5Ez28aCGTywFVRWGY=,tag:MZI5vXQwhP6dctcgaps4rA==,type:str]
    AI_KEY: ENC[AES256_GCM,data:hlwS0Xsx9D59Hg/xbW9fahv1d+98zjNwVRAQl3gtKl66Xj2OvZoCpnZgSz+gUzbwztg1bf4mZSnxmkH3rfbGC4KWvO3y7pT+MA==,iv:iRHids/V2Zv1Tun/pNRHuwyIMIu3Ucmj6mDyqulZvrE=,tag:YOVD1sTVRD4Bdq5gI0O/Ow==,type:str]
    RCON_PASSWORD: ENC[AES256_GCM,data:ZJ81hs5TIvsnItgdKBgjZ3CE,iv:0J59xioFobZfYOg/m7YQ9ElK7V3bHlBkJQlVDrSxMqY=,tag:hdsolXIjvfCZF1DroIQwgA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h440ezlz0n2wf57mvdzfes8hglf7p543ryggjwgywlwlrwlmhczs4qtdzz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKSlYxcEsxVWZmcXVvb1RE
            T205UWhkM0VmRDBhYzBzWGZSK1RxNWZVMWxrCkdIL1BPQkY3SklQY0RvaXR4WXAx
            bllRajd4elR2MFYrMFBQQWs0cEdHd1EKLS0tICtYeCtBNmJ2Yk8wRWJOa3hRdy83
            WTNaOExkSXp5elorREVPekxiWFp2c0EKESunwX86JS3Fg38fYuTbiPeL6xTHCsPp
            jSoqkaAwFPmfZlA7jXaW3U7esHcRC7a54YJ0RbcGzXlFPegHDKSiOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-19T17:05:34Z"
    mac: ENC[AES256_GCM,data:MsBcKyWmGdhf+VXskIJTRucBqQXmSyorexi/9w6nz5uA26yx2lBJUAugfGzIDxAwJUp941RgdIq7rtwBzNoBkTm/1y00SOx4o3HV8rOcZUx0xd11KkXdp52iwPgiQ0cqtIJL+OeowfIyGmePERJSH7htK+l4wDj4TyXr6ZtzJJ4=,iv:Dc87mLqvhhHr0gt6B1AcSPE5PvfLE8pFKIv9dvhdwv8=,tag:3VdzfH/pnIgoVzkSkvvqUw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
