apiVersion: v1
kind: Secret
metadata:
    name: cf-secret
    namespace: infra
stringData:
    CF_API_KEY: ENC[AES256_GCM,data:2XhwZG+EdzmyFnTUmHmrsaHvhmjhrD7bKm1mbVrexQljgDGIO/1VqQ==,iv:ODuX+0zCnnkaOD/6xdGDWJKWZ3/sYSLOtXfsRdEdMOA=,tag:zjLIKMkA4fw4xKta9WKg/w==,type:str]
    CF_API_EMAIL: ENC[AES256_GCM,data:FQnYwxbl2AcEfCa8IBhNN9RNKoiLEQ==,iv:VKCQz7x5XqoLQbdqQ2RvcOANtRfiyOz2TLkM1PO5XnI=,tag:LTqhGtn9q/soHLruAQtWJw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h440ezlz0n2wf57mvdzfes8hglf7p543ryggjwgywlwlrwlmhczs4qtdzz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2TUlHVFVFUU9vUGpwQmdy
            dWwrSTNzNXlNLzRyU1IrVnRSU0NEQXk5SWo0CjBSMmsxbHJOZHR0akJ3aVprbDBU
            Z3piaUExYXZqNndlNHk2Sis0TkJmMTgKLS0tIEZrVzNrbm5tWGJobXJqZmhLTkJY
            MTN4ZXgrWTI2REJnbHVjREoyUUxxa28K5UzVOsZFdf1b/afroOaFN+3RoPK6AIfm
            sI0ruGTl4WtxYeSvVvcpZoX0cV0+dQH9I2Ka/CXRSIS3d9BhmDg9KQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-20T19:11:23Z"
    mac: ENC[AES256_GCM,data:ZBk2X9wJg+7K2hQuG2mIyetia04QjoDwCRRaa+0JbppNb5W+4DutQGj33dwCKm0b8GsOC/yEW8IiY4SMUUy4220tTQUv/yNJHUdy83J+nL/AAsEFRZtn9KLA9GgiFDb2i6YaBCod36ZUiyWL83YZDPxiH/elq2OAGqqdYl72hDI=,iv:U2/Bptofw4uLiE4WYZ6AgzfNqB9Pt3DBj6oUKXesZV4=,tag:LkAY+Vou8AZ2ztgjud0I7Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
