apiVersion: v1
kind: Secret
metadata:
    name: pihole-secret
    namespace: infra
stringData:
    EXTERNAL_DNS_PIHOLE_SERVER: ENC[AES256_GCM,data:nAkxAPwUXmRM24sSX2hPfaS1,iv:WRN0o+mjwNjcsXY4EYyiLGRkFvFjdv3WO2NokpMJgnk=,tag:H90g+mmTXhprWKOVz/6xQw==,type:str]
    EXTERNAL_DNS_PIHOLE_PASSWORD: ENC[AES256_GCM,data:7Uq4rNRVBALXK6cK,iv:Ons3apHMXAXtmLYM96bStWxoDFZEXzzqMRcG8MDPsE0=,tag:WHnPLh0JjuTtye+N+pPsbQ==,type:str]
    EXTERNAL_DNS_RFC2136_TSIG_SECRET: ENC[AES256_GCM,data:7YUBVPGdEZopBIi84pqe/Z32uvGsq445s5mtyi4I/p/P+JrFwqk+VTEEJh4=,iv:cAhz91jN01/BMNlPY2pWMdp+JfGBj+nVWbilrj6TFLs=,tag:R+jkmPly8ZvE1Ltf/ECFFw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h440ezlz0n2wf57mvdzfes8hglf7p543ryggjwgywlwlrwlmhczs4qtdzz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXZTRaMDhvRDdNbFRMdFRM
            RnpQMnp5dHNwS2djS2JWaFplb3IzS2E3MVc4CnluKzVDSWMrcldmNFYycSt2alNx
            ZWVIWVpsdjdrZXcrTi81RUxuRUJFWVEKLS0tIDczRURwSWV0U1l4M0J0WjNaR0Vo
            R282UlFnNlVqaFVZdGRoTnlabFJDRVEK2nU1YYQrV/57sRtjryKLxGEGhik216ga
            I3ZIBKfLgqB3dW3uo3vcq4VjinXTyDQgmQZFBmv4FogF0b0D2EoG5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-10T21:50:38Z"
    mac: ENC[AES256_GCM,data:H2Y/pF48xu8qG7O0W5xaOIYQ2L4EDqyD3fB5rPHnzCqznihCd0xIt1zzCfyVLrorqWHO4uTYjaRLca2YZcuv2a7YDemIWorqzM4auyo1houmdHNWT1GRKOOXtJQIyFwu5AlFoVHo+e7KuXAr02eVjaldB4vtvR8hiEx4GNIpQF8=,iv:81xHaCoeJJCO8arwklTEQFMK5zwvgc7s83ARAJHsIRA=,tag:6UpgvNaVZ3bi/hQ43MZbog==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
