apiVersion: v1
kind: Secret
metadata:
    name: pihole-secret
    namespace: infra
stringData:
    EXTERNAL_DNS_PIHOLE_SERVER: ENC[AES256_GCM,data:i5xnMlH5fHU5ZIkSN+ASUodV,iv:F41pgHwH83qKGe2xIHkhJ6Qqq/9kFfsFAt82jCm0ZgI=,tag:cvQyaigpXo1MjJKyfpG86Q==,type:str]
    EXTERNAL_DNS_PIHOLE_PASSWORD: ENC[AES256_GCM,data:1iEse8BWydFhY8BT,iv:qloiVl7lD4J+meVAU+hnjgDzPIzjJcO/UXoS/c9lBYo=,tag:u630Utc7QBDtlio475DSxQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h440ezlz0n2wf57mvdzfes8hglf7p543ryggjwgywlwlrwlmhczs4qtdzz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxR0M1UENCUE9mOUVIaVFp
            NG1LZ1MrZzBkb2wyMmNxUjVmMTdzM0UvWGtrCjVoRWh3M3hkT2ZWdmVCc1JiMXB6
            T2tnVFdVYytVY0VUZDdMcTJZU0JBRW8KLS0tIDN6ck1lYlF0cEhYM3VKOFc3aDJx
            WUNFaEVqcjlhdDVMdHNrWjFhbzY1eDQKOJFXEs8PdiHG0q1YS44MZjsnTUCq+rKw
            oMPeOt0Kc2c4Am+Znl9PPeDP3Q//AVsJqL40JwDT8yWCXoeahoIs/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-19T12:58:56Z"
    mac: ENC[AES256_GCM,data:qn7d7Dko6ShIwnisUKxopIJZ9mbVTHazK8wFF/63wOwK8zL4ZgDTDcANL2kpWj9B6zb48eeM/h9CuiJIPIU1Kg/cYhm8Vi64czz1pJes3cRzJ72trYODFPZ5c0tz9tQlIXFQNN4jAJpVM/z/Rxl/ZYFJc/fqyfH28eckLwG0qw0=,iv:CIYTy/24Nlwwu5IgxsHmtIyhSkIs7Ilm17GwQgB7DIM=,tag:AUnWzRqfjwUcE9YG9vx2Tg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
