apiVersion: v1
kind: Secret
metadata:
    name: technitium-secret
    namespace: infra
stringData:
    EXTERNAL_DNS_RFC2136_TSIG_SECRET: ENC[AES256_GCM,data:3VGMScBA7+d9N/qLOL7smOeuBwCJmWMSwC8ArfAg32hChXDF1DcFGqP83oE=,iv:CLSTS8rh8TUlnGJrzbO/6fzYMfnJ3UgfydMchw+G+W0=,tag:9yQvm0KquXAu7Mv43kZ9bQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h440ezlz0n2wf57mvdzfes8hglf7p543ryggjwgywlwlrwlmhczs4qtdzz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwMnRCK0FlYVExYjloQThk
            eWd2SXFXUGk2LytidGNvQXY4WHhQV2hLdDBrCi9sQ0hRd3ZpaTh0T0FnWFMwb3hu
            UFhocnNzUktCOFoyeGM3Nkowc3ZPR1UKLS0tIER1ajRyMUw0MnZuUlRIR2lwSHBO
            TFdQL294bHN2RmcxZ05Zd1hCK1NkcUkKqqAq6sRIu+wQNBpBU8Pjz56jFWgtr5/J
            ERf0WD2FLmb/nR2hG1WXehTRG2+T2+fCtxb47qyCI+BKYPGBg12hcg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-14T22:38:11Z"
    mac: ENC[AES256_GCM,data:joQmYRsON/SXvMAQlzqKKneiObjibkW+Bzd+covIBHWk98+8HV9MIuqm+Fxb+xAIpYK2SHHWK7fhwECC4IhjstQCqFMSgZfx+5cqNOYqqJRICKE1Vwp8rxfPfgEDm3DQYBCrgV88vU6B8ZdVIWvSjZ/3vzbiEoeOmsm60h47p84=,iv:uto1r+OMogVPfw8W/TILXlN05faEly2zDEsfFfamQN8=,tag:U2e3EOXPW3opfYnBeATIqg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
