apiVersion: v1
kind: Secret
metadata:
    name: technitium-secret
    namespace: infra
stringData:
    EXTERNAL_DNS_RFC2136_TSIG_SECRET: ENC[AES256_GCM,data:S0IFPQdQYYkgvTrF7mX5bf4yB8TiTjtcCfbsPiJf1WEfs5dHfKawZC62hiI=,iv:tDOOZk7jKRdTUG7PYuadlG1vANEjVQqMDbyoRAiFHl8=,tag:C03egZoJ6KXytDRV1dk/Qw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h440ezlz0n2wf57mvdzfes8hglf7p543ryggjwgywlwlrwlmhczs4qtdzz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqdHQ4S2VDMUtoNktobTdB
            K3hUZUZ4OWZUSjZVNTBJQlQ0M0luelkzUjBrCmhXRWRaOCt6cWtwcFpkWXpNOUxZ
            TlJtRG1yUU51OFFTcWxWOGlmTkFLNFEKLS0tIHpvR1ZJOHFTbGtxWnRublpZa1hC
            blJyODd6Y3M3U1JQNlFPWU9aSVZiT2cKEEM1i6zQj+/al4uZSVecYLDf1acD6vOx
            vsJD0EALjqVHRAeyRX+VHPh0Pj0dzgJNTul/Uj7Z/B62OUGW1Jt5hw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-16T17:45:50Z"
    mac: ENC[AES256_GCM,data:1V3KXiV0onuyt2HQlrv+8j9DYqJ4wA6n+sOVjtXAEjlSJ8NtgC6L0Qbl4zvkjzSYjiiluE/5y5pwM1Ft43ZrK4Qvy87oFQfROzqt4XnMUxzyxBCNOXwfDV0WfmIuZZusV+QfeqQSVPQbln6pqG3a4nZM1nIQ8L4r2OehZjSZvNA=,iv:30kJ+s1Mvhc4iX73YG+Oy3daSs6MjOeBap6KSsQVQvU=,tag:u9y04LNksB8/S7Bg6SrkXw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
