apiVersion: v1
kind: Secret
metadata:
    name: unifi-secret
    namespace: infra
stringData:
    UNIFI_API_KEY: ENC[AES256_GCM,data:/B1LE3u0JzZXt6qONROKGnb93tlTm8jwsqQOKNArLfo=,iv:OECFXYOWoKMHYMYF6gKBZZ/GF5jD9aqoYPNA3FWNVgE=,tag:GM3jVz4BfZ52sFjdyNN67w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h440ezlz0n2wf57mvdzfes8hglf7p543ryggjwgywlwlrwlmhczs4qtdzz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqOFFINHBHTGozS2gzL0M4
            bGhmcUEvdjFFMTRxYkZheEpqL2M1YzZ6N1JJCjh5TUIxQzZrdzZZMWFFVjhrYnNi
            S0pzRDRWMExSQjFISlJxZnNSOXZpWU0KLS0tIFVVN1BGU2lpWnJWeUZsQ05JWWxL
            Yi9MTmJiTkMxRlBaRDRMbWxYN0RQNlkK/LL3QFgPhMmpLJYrOgqVbeFma5/AFAx8
            RD3E8XYdxXUzXyG7NdeWxK3V0ggMl5v0XOPrqb4MoWMvR1yt/Kvp3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-15T23:20:09Z"
    mac: ENC[AES256_GCM,data:x13LDH79YLfzbZ/LvpYchK+TPIg0pamYevlKKK35MVHuDSb5dSTSDyHUIhuQnbb8PzeYuBrVysxD9xr9rfbGHjqNDF/OqKriegME7bOB02QwFcs63uyjLJwxTL8DUjavOvZDaRMg7Rf9i5G50W4Nn/xYS0Vx/B7dZ2vggEuxPBg=,iv:kdPRn9XirX+e7xBT+weY7YLBAiPVLLZAoxx9QrwDCSg=,tag:p3kgFSV3hoJPWUrAQ/bmvQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
