apiVersion: v1
kind: Secret
metadata:
    name: unifi-secret
    namespace: infra
stringData:
    UNIFI_API_KEY: ENC[AES256_GCM,data:roBf6zAnDFL1kMENu4h3kOpRjwncY86GZnjoskqA4vE=,iv:Ww62LAaf6zseyhCs2VBhHa9rQPKcK+Udjm0gKV84NoQ=,tag:UZ2SoYNxfn4uFJWL97J2Sw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h440ezlz0n2wf57mvdzfes8hglf7p543ryggjwgywlwlrwlmhczs4qtdzz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsS1RkWmxtUVdkRVhRc0F1
            YTFrUnhrS3Qza1dNSDdpUFdrakIzUDdnampRCjROQ21tRW5wWVNsb0MxeUZYaFBh
            Yk1IOVhZZWZxa3pYMGljZUZOR3FEQ3cKLS0tIERxUTdqQS9Mc3dHVGdKR01Xc3dn
            ZkVlMTM3R3B4SExpVDJhZG5yRmViOUEKLVJKVZmaall0x9r4eFGiy9Lo6Jw7aXZk
            Rt28OXjgiD025QrbaB6f1b3XYXzKJSdqBsXqO9OASw26a09aq1sS1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-16T14:38:26Z"
    mac: ENC[AES256_GCM,data:WANRY7we7iFIKybYierzMzjxyRHXnaHBmj6mJdtTkBo7IpOd19wkLdspzKwYaIiklfut+M/VIx6jy8bQ3kAbk8q03iMSUoDS+U4zOkUqyV+Pw/93XcjkTXIR/zPEAYPBBedxUl0Z631+WKHc5tGf4ZYcTeqPMvH81nThX7Z+A6o=,iv:DtjRUllKs443sFCMf4n79VKaqBjWYLyn2qnfhQAOwVg=,tag:8FyNSQIq30M8Q4+doXq4TQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
