apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secret.yaml
  - odoo.yaml
configMapGenerator:
  - name: odoo-configmap
    namespace: apps
    files:
      - ./config/odoo.conf
generatorOptions:
  disableNameSuffixHash: true
