apiVersion: v1
kind: Secret
metadata:
    name: odoo-secrets
    namespace: apps
stringData:
    HOST: ENC[AES256_GCM,data:Jd3yVHlh7XCzvXoG/wtgvZBXTw6cMYFP7zY7/oOyN60=,iv:Onj5pPrLwEyBrIjtLrfuSLGMjsfnkV5tc+Vg9IvZvC0=,tag:Fl9gITYfob/yZL2byeY8RQ==,type:str]
    PORT: ENC[AES256_GCM,data:QmigCQ==,iv:2K37gL1jnHV1EpAuo+2ZXJax1zAEel0D6dH7Z8Esg/Y=,tag:t69qXLSa/NFCrwNtnmoA3w==,type:str]
    USER: ENC[AES256_GCM,data:UIbSt3Hkug8=,iv:mJtYNln5KatxE2dza5DEAEhGXPnujys9GTEXL7qXPfA=,tag:wZ4AmHsvo7BEUZrFIqtobw==,type:str]
    PASSWORD: ENC[AES256_GCM,data:9kLJM0qXWVd+GE4M,iv:LWhqJjLRnQA18zf8PDKIP4nj6qsDN3Fy+5C1keSGFxk=,tag:JP6uxNoZFhIbnzOrGsuzCQ==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:5If9og==,iv:lUBx49EIfHdQb0VnKcj3E4b+AkdAjsiNHzNhb5bm7nw=,tag:jUklVjaIkPcnQMpVpY5hAA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h440ezlz0n2wf57mvdzfes8hglf7p543ryggjwgywlwlrwlmhczs4qtdzz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2T0E1dC9iNXZ6MWs0c05y
            VmlQTlpNUmR6bkNaU0dEZFI5cjNKUW44VkRRCndIOE1JaXFXbVhZSlBMM0R6VjdD
            SEhyY09OZ3hZTkVucnVYODFkdk5wL2sKLS0tICs0TFN1cWVpZ3RVZEtSUDN0UWth
            Qk5DSjNwYitvWWI2aXdDRGhlRElRUU0KkrXd2PcR8o6zsD0691X2Ira167hPNoOH
            Ulr6V2ZQGb8lEzkwsuKefKr23cBkbseOrzE70Ug5oXvKPFE1YRdyVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-14T14:25:39Z"
    mac: ENC[AES256_GCM,data:aSZYA5e5u496TLqMEQOK+A5GHtnRsRLdCzazkmCYf/4vp/aX+gRUSk3ehAch7MziOBymt7z9HDJZKklZfmBGHdytSOCviaQ2uFmRAzpXoRu00UYoB30TxJvOXFA2wy+AE0HXrXrS6CvhAQ+tPRdY+QudMXmE2lJ+F9Gh6lb9MfY=,iv:X8UvCbp7NK+n/7Fua0i4N08r9UAR7+akkistEyo3IMI=,tag:AQQaVZNFZ4lD6g74/FQlsQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
