apiVersion: v1
kind: Secret
metadata:
    name: odoo-secrets
    namespace: apps
stringData:
    HOST: ENC[AES256_GCM,data:T9omMU0ldFD3WativBDWpyCEnxdgbC+oPsPH0S56sIg=,iv:V2inTsQjvNFtYbDQFEp0XwtiWk6Kv+t4zSh0zOK72yo=,tag:vcuwecwkHifozyB/Hdc5Gg==,type:str]
    PORT: ENC[AES256_GCM,data:bwz21g==,iv:EKjU9Spwv7aBv4SPWCYuuuAEUcHh2G57eKtNlfxXr/E=,tag:gZ5iHhVPC8wQvb7GBOfghw==,type:int]
    USER: ENC[AES256_GCM,data:wa5v/ZFVPms=,iv:A/Wf2I/ISxMEYXiT8gp9FnUw6+JGZW29HyjMBnIrAEs=,tag:K8GOI89JzTE3wCpAUjnHgw==,type:str]
    PASSWORD: ENC[AES256_GCM,data:6gztoTjCmAikREwa,iv:/DYOGCTq5OBwlpCCBxBDd5fEr758mfsb70n65XhL2L8=,tag:v/kGyjegHZQhWZYxeo2FFg==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:tF3k1g==,iv:0pS6bJr/zH/L8APGTYEXi2ztdR94H6fF5cF7+jkUo18=,tag:UpolQz2zBrvSORyusp2Qrw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h440ezlz0n2wf57mvdzfes8hglf7p543ryggjwgywlwlrwlmhczs4qtdzz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpZDNHeFpDNDB6ekt6YmRa
            NDA5eFhrYTY1NmduNWFUZnU3YjdUUjJWZzI4CkFHeHZhd3l1Mld0a0NpdVJxeWFr
            TkhqQk4vTXE4NU0wWXF3QmNkcmFieGsKLS0tIDFmMHhrdkhJemQwRGpyYy9rNkk2
            TENyWGt5WkRiei9vWXJzSnZ3ZS9nVnMK5wTEEsedqCP/nWqm8a4afsrY0E34BWpD
            L6TM32jU/V7JMUOiWXtfdcM3l+RWfy4BmgBpxGEghFqeEQE3uOGwcw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-14T13:10:07Z"
    mac: ENC[AES256_GCM,data:1nrqZEwWv0SJS63RWL172yw5qHM8LTPE1ZOTzjp54IHk8LcJKj6QR/8AngDdxFyY4jNTsDbQJ1dmHf3axEV3vSvTmGaFlmKVqFhhhvXHAbq5nBIzzl0XGEVz7qBSlss6KeLqs1sex5wut08XqvOobuTtDaE0MmxoNo/gl/3wcS4=,iv:r6W04Msjl0Xy5awRtRHrakWIC2BfHIkNamRIr1mIaO0=,tag:6diQHoLRwD5SQQfcxTizuA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
