apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - generic-device-plugin.yaml
configMapGenerator:
  - name: generic-device-plugin-config
    files:
      - ./config/config.yaml
generatorOptions:
  disableNameSuffixHash: true
