apiVersion: v1
kind: Secret
metadata:
    name: vrchat-jellyfin-secret
    namespace: apps
stringData:
    JELLYFIN_PASSWORD: ENC[AES256_GCM,data:DrDfCoE9RL+BPNkdm3j/ODz7AYnCr9TjkEO+n4DwV90=,iv:GJzT6d6EVgxis+96Q/YcNqRfyFLf6U/iAN3TfN3L+1I=,tag:Y/7HvdhOp33VjB+fNswWpQ==,type:str]
sops:
    age:
        - recipient: age1h440ezlz0n2wf57mvdzfes8hglf7p543ryggjwgywlwlrwlmhczs4qtdzz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtSnBCRUFMOTlhU1l2aGp4
            ZXdyc0xUOFVVSnhYUUlvNWROajkwYU04OERjCmZjb1dxLzZ1ck4yY2tibUo5WkpX
            Q2FUdkI3cmxVSCtJTGJlQzlVa0thQVUKLS0tIEFieXdkd21VTWJENzB2VjdlZTdF
            bEFnN0FFVkw5Skp4dmZ6S3VUdno4dUkKeFp/2pch/AIKWfdS0102PZiTWKPpydvl
            4KOiVbC/YmXkvqz+jWsnvRKCJLRtoS1Zc1mOWqwTTqDSo08Q5xy0bQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-13T19:22:17Z"
    mac: ENC[AES256_GCM,data:aVxB/saR45OPBQHxCIXl6m23i2I2icvgnyhOzpwDeptGeuKW8RqnRqMt0yc7fBx3ZkTNRpx6yoNQOimV9gTyA2srKP5J8tYkv1kL/Bci/HR8XQ5ON2ifoQzglJbCKD95/MNOkbesHrRRJhAphYsKIym+f3SoWeOGaWYZaHER+3c=,iv:bvu7kJJqPQGNYKA+vm7v1Djhm+r+49IdDZByNS4py/M=,tag:yth4hfJCKzZeWPN3Ybxttw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
