apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jenya.lol
  namespace: infra
spec:
  secretName: jenya.lol
  issuerRef:
    name: letsencrypt-dev-wcard
    kind: Issuer
    group: cert-manager.io
  commonName: "*.jenya.lol"
  dnsNames:
    - "jenya.lol"
    - "*.jenya.lol"
