apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ${WAITLE_DOMAIN}
  namespace: infra
spec:
  secretName: ${WAITLE_DOMAIN}
  issuerRef:
    name: letsencrypt-dev-wcard
    kind: ClusterIssuer
    group: cert-manager.io
  commonName: &commonName "*.${WAITLE_DOMAIN}"
  dnsNames:
    - "${WAITLE_DOMAIN}"
    - *commonName
