apiVersion: v1
kind: Secret
metadata:
    name: github-secret
    namespace: apps
stringData:
    github_token: ENC[AES256_GCM,data:mo/GdZHgM9b3VLlxIiZfW3EM3a2AfF6dLDLasUChpOly7+WeMX22Mw==,iv:Zya5MCM9891+z08fvlfX8S3nEdXurO0Fve7tfSkEAMc=,tag:NdDpUs2xRAlONYqYQCXMwA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h440ezlz0n2wf57mvdzfes8hglf7p543ryggjwgywlwlrwlmhczs4qtdzz
          enc: |
              -----BEGIN AGE ENCRYPTED FILE-----
              YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjU3I1ckZBbzh2bzhMZ1hl
              emFXc2F1Z29HelJFenFIazVxcDJmNWcrbW44CmJQak9lcmR6aDNobENBUzVWWWJX
              MzZzb1E3NW54LzlxK2tPOVV3SmtDZ3cKLS0tIFJXZHJ3d3JzdnROYkV1RWZ3YUFo
              SDFiRXRkVHpCeTJWNUZSM2lDNzhFK1EKL7kvtoOczW/ZDF7nUKXrWq8Whvkp7LGz
              ubCcWLGcynENES2Py5yLThZVeYW1O6oXOJQsob3eZC7PIv+qhbg9Kw==
              -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-18T10:40:22Z"
    mac: ENC[AES256_GCM,data:8mrB4I1AA5NAwrdriSeMdoPD0jIb5ixsBeQzqOD0Eyg3y8HPB3/PWKnGHhUT3nalMizgRhX8V6WyahqV6YGpqS/c3HkykJc1PovAVXGOQkfVoTNfn4r6NxtoM10oPfSCq8NFkie28EvL9lTQgCsMdx5AQ9MnGHfQL6HG98vOf4k=,iv:lA9vGLbCBgtmWFPiHu9F8Zs88N6kIqNBgmP5goS1iLo=,tag:Dgyy/bW5niuUExRRj0c+1Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
