apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns-pihole
  namespace: infra
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns-pihole
  template:
    metadata:
      labels:
        app: external-dns-pihole
    spec:
      serviceAccountName: external-dns
      containers:
        - name: external-dns-pihole
          image: registry.k8s.io/external-dns/external-dns:v0.15.1
          # If authentication is disabled and/or you didn't create
          # a secret, you can remove this block.
          envFrom:
            - secretRef:
                # Change this if you gave the secret a different name
                name: pihole-secret
          args:
            - --source=service
            - --source=ingress
            - --target-net-filter=192.0.0.0/8
            # Pihole only supports A/AAAA/CNAME records so there is no mechanism to track ownership.
            # You don't need to set this flag, but if you leave it unset, you will receive warning
            # logs when ExternalDNS attempts to create TXT records.
            - --registry=noop
            # IMPORTANT: If you have records that you manage manually in Pi-hole, set
            # the policy to upsert-only so they do not get deleted.
            - --policy=upsert-only
            - --provider=pihole
            # Change this to the actual address of your Pi-hole web server
      securityContext:
        fsGroup: 65534 # For ExternalDNS to be able to read Kubernetes token files
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns-cf
  namespace: infra
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns-cf
  template:
    metadata:
      labels:
        app: external-dns-cf
    spec:
      serviceAccountName: external-dns
      containers:
        - name: external-dns-cf
          image: registry.k8s.io/external-dns/external-dns:v0.15.1
          env:
            - name: CF_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cloudflare-secret
                  key: cloudflareKey
          args:
            - --source=ingress # ingress is also possible
            - --provider=cloudflare
            # - --cloudflare-proxied # (optional) enable the proxy feature of Cloudflare (DDOS protection, CDN...)
            - --exclude-target-net=192.0.0.0/8
            - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
            - --crd-source-kind=DNSEndpoint
      securityContext:
        fsGroup: 65534
