apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - grafana.yaml
  - ingress-nginx.yaml
  - jetstack.yaml
  - twuni.yaml
  - bitnami.yaml
  - tailscale.yaml
  - bjw-s.yaml
  - external-dns.yaml
  - unifi.yaml
