apiVersion: v1
kind: ConfigMap
metadata:
  name: recyclarr-configmap
  namespace: apps
data:
  recyclarr.yml: |
    sonarr:
      shows:
        base_url: http://sonarr.apps.svc.cluster.local:8989
        api_key: !env_var SONARR_API_KEY

        delete_old_custom_formats: true

        include:
          - template: sonarr-quality-definition-anime
          - template: sonarr-v4-quality-profile-anime
          - template: sonarr-v4-custom-formats-anime

        custom_formats:
          - trash_ids:
              - 026d5aadd1a6b4e550b134cb6c72b3ca # Uncensored
            assign_scores_to:
              - name: Remux-1080p - Anime
                score: 0 # Adjust scoring as desired

          - trash_ids:
              - b2550eb333d27b75833e25b8c2557b38 # 10bit
            assign_scores_to:
              - name: Remux-1080p - Anime
                score: 0 # Adjust scoring as desired

          - trash_ids:
              - 418f50b10f1907201b6cfdf881f467b7 # Anime Dual Audio
            assign_scores_to:
              - name: Remux-1080p - Anime
                score: 0 # Adjust scoring as desired
        
    radarr:
      radarr-instance:
        base_url: http://radarr.apps.svc.cluster.local:7878
        api_key: !env_var RADARR_API_KEY
