apiVersion: v1
kind: Secret
metadata:
    name: tailscale-secret
    namespace: infra
stringData:
    client_id: ENC[AES256_GCM,data:EIYdNj6WXg65NKWxd3su/OI=,iv:O6Gorr33WlrnkIX2/TCYDxQUDbKpbER2ndAIe8Iv9M0=,tag:8BPmX83pDFFhZ269iCcsmw==,type:str]
    client_secret: ENC[AES256_GCM,data:xxgs/lXZ1IXsi0/aAAmjJIBVUfikrx8anWNG2iZ3I85f6CZoI6Mf2CwM++dJqgkfX+5NRuziBMjQjEo07ScHJA==,iv:CmlcVrOHS5u7vqPoWt0E3OlPcNCIw2SYpRHv6P5E92Q=,tag:mZhaqmEm0HJQvsSmzLCmUA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h440ezlz0n2wf57mvdzfes8hglf7p543ryggjwgywlwlrwlmhczs4qtdzz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkMG1XTVZWNENVVktRc2Zh
            bnhuZWErdVN5d3d3NldSOVltU0JMS3ZvUmpVCmlzTjl3RzdMaXJJM0lKNzU4S0xG
            ZW94YWN1aGlpMXZvTEVQTGZXeUE5OGcKLS0tIGNQSjF1RXlqSm8vTmZQd1FkTSs1
            dmVFZU5NSWh2a2dBK1ovM2VxRXJ6Z0kKI8rrTUtAOS7qTbc5lN7QZZke97XgnMP5
            ekzNq7c8J9MVpb2B65MlL35yZMgwn5Yx1/CWxMsmOz4gscodvI59xA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-20T18:03:44Z"
    mac: ENC[AES256_GCM,data:x6ZJRqXVYrLfaeK853BGPCBr0R8tPQyKgL1C2dzhvbUs0/VMK7UehMT86/XrRW48pAgQk/y1W1x4fsk3v/Kr7ZeWJ32pe/VGpDQSepWdSeRY7fBnfHwb78mq9e5SP5ZLsZSiAYxPiXPZYijumH8ATIFPITV1DnLqtgI55xNZhdk=,iv:omg+TIcVAJajqKarjCa3e7eJvNPCCjlSY290RzepfT4=,tag:t7jOwahCy0l/RAeQNF392A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
