apiVersion: v1
kind: Secret
metadata:
    name: tailscale-secret
stringData:
    client_id: ENC[AES256_GCM,data:6imxGgEhP8FDKJeaEkqtbzQ=,iv:rhGYUYQX2cjEuq720+/lkmqjHMe7gUA7jmFsf2XuPZ8=,tag:49vYPpz4/nMrKKYi2RWnzA==,type:str]
    client_secret: ENC[AES256_GCM,data:lZ7IV8f/+dvj01Ih5/QsawSU/MtUS63tVNih/Dg2p9X8JhW9SP6ydc6Nb85h/kmnWhyqq+LSCCz1cWHG9uP+aw==,iv:PMpNHANaz0yiOXkxF2RbgSasTpzbuvUsYQdJx+0NmRw=,tag:wmDOaDFTaq7vQLSXgvdmoA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h440ezlz0n2wf57mvdzfes8hglf7p543ryggjwgywlwlrwlmhczs4qtdzz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKQ2JCM2tZVUVFenMweEFM
            K2RTNVFZcDhXK1NIckJjU1pObU9CNGo2a0d3ClE0Mmg4WTJ1NkRjQlBvMGtDWXV0
            eXBGTnhKVEgxeHhBREk0bm1adzNiV3cKLS0tIGlJTXp2bGxZaFNxME1rWFZGc0VJ
            R041a1JCSXh2UkdSK0MyOGJHS3RDSTQKZT7Em/ivEbACGXQqA8WrShGykdh6+Out
            E7ysr671rUrZZPtItk0nlXz7uz9o16g73uS8PjOqsbo5QdTph5zS1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-20T18:02:08Z"
    mac: ENC[AES256_GCM,data:J0TYSlplydAWbV49AuUhFpcFownVRcGEN3TREkNWgeQ+tY2fgdzOCoR+G0azuFroiVH5lzdOeeoVQ32y4QHMnB2dfWFsrdAgSmbC6/ajzr2oHLVfoO03ynUNW3Iy5EeI+Yduvsry6lSxhO/g34UkPfcfsqAxSjv3+PwTMCQRipg=,iv:E/JLY1q60Is5rLmHQPG8b139FLKTdpVryq2HoeO5B+w=,tag:05qqWWjjFzn1NeAocIrp4g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
