apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: ingress-values
  namespace: infra
data:
  values.yaml: |-
    # paste chart values.yaml (indented) here and alter as required
