apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  # - ../base/monitoring
  - ../base/tailscale
  - ../base/ingress-nginx
  - ../base/cert-manager
  - ../base/external-dns
#  - ../base/cloudflared
  # - ../base/rabbitmq
  # - ../base/postgres
#  - ../base/redis
  # - ../base/generic-device-plugin
  - ../base/newt
