apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: cloudflared-tunnel
  annotations:
    external-dns.alpha.kubernetes.io/target: external.jenya.lol
    external-dns.alpha.kubernetes.io/external: 'true'
spec:
  endpoints:
    - dnsName: external.jenya.lol
      recordType: CNAME
      targets: ["${CLOUDFLARE_TUNNEL_ID}.cfargotunnel.com"]
    - dnsName: b.jenya.lol
      recordType: CNAME
      targets: ["external.jenya.lol"]
    - dnsName: *.b.jenya.lol
      recordType: CNAME
      targets: ["external.jenya.lol"]
