apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infra
resources:
  - dnsendpoint.yaml
  #  - secret.yaml
  #  - cloudflared.yaml
configMapGenerator:
  - name: cloudflared-configmap
    files:
      - ./config/config.yaml
generatorOptions:
  disableNameSuffixHash: true
