apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-credentials
    namespace: infra
    annotations:
        sops.kubernetes.io/encrypted: "true"
type: Opaque
stringData:
    credentials.json: ENC[AES256_GCM,data:GH1kUcFAtJMB+qgydof9Ep+CxQUdA+VSCGm576zWo/6fiFVujYI2Q7FwXSnj3zKLniO4PIzpRdUj+l8XrO/RCZ9uY9aFO6eOoTUowS8xvGbAEZ2EiwK7MZo/7mcL6Khpug6P4g90hk1HKsRNK65UPdQFk2aqry2uaz98I5OPcPN+oxMRCJ4RxucOKM7ER7Y5eiYPIA9smQutkf7whEmp6tb0DFy7oXwvwb41BhMqIoLlCTQ=,iv:wJUSMZeWocWmXQVXdGJVxsLmjdY+IHtY9Mp0YnGYLwg=,tag:ZEBANMkZJDGZCs23EdBqFA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h440ezlz0n2wf57mvdzfes8hglf7p543ryggjwgywlwlrwlmhczs4qtdzz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByVEVveGRYbEJqTGhNaXdj
            QmVLc1ZnWG52aVdqa2d5dkxOcTUwSkt5Y0hjCmpGRkZCaE14ZWdoZW9OdkZxVVk5
            UnJGQ0dqeG5kOVEvL0hXQzVBTC9iU0kKLS0tIGFrZ1dLWS9OcXBkY2pFZHBtcXpB
            YmkzNVN6a1YwcTJjQjlWRk1ZRyt6cWcKkqlGNQGjeN6YI542J62gRwdUNd0qAsBp
            SGFlVo7IP0bGRjTQ2jwVrcshcgvAJx8HgL0STBBQBzmAP8Uld+ybdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-03T22:05:59Z"
    mac: ENC[AES256_GCM,data:AKzmlWs0Fitg+BQBlOWOY8TOPAxu19r2xhxn0jqPmBuxPYJMaEsXb5PyJR+2ICKHEsEUXkL+EAa4ZLopmZhUAhDtSIY3LCkWg+lVB1TuAFpCi1gqbNMTPssjwa+M87dHkhJWkjxlX701qLjFGCv8+834EK86SzfVMWR/RqAziJw=,iv:NnURLucQoRyrSKV48Gj7s4RuvJQveKXmjBiw6sUL94s=,tag:ZisEd2LYgRtstell7zI9NA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
