apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-credentials
    namespace: infra
    annotations:
        sops.kubernetes.io/encrypted: "true"
type: Opaque
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:93vI3gfAdszymUGTJG/2Iq13Jncls4B7MytaJLl0Nb5Aqb10,iv:g1sAQ4zER/7bjj+2V1hltXh/RJUKiV9cHjWsJcwjmJA=,tag:VNDK07rWc8h3KvFWcbq/KA==,type:str]
    credentials.json: ENC[AES256_GCM,data:Dpff4+M0v0FXp5y14uXDUHmNJJsu9tcKG6zFUc6eT8+2+1iyrE/FMv+sPtah5Y0hQ8GAWFGG3jgl4uYRxCA+tu7rbqnbiWuq/NiGLtHUFhp57irMaYzjCB0AuCpoE0tF0BgaQZwjoSFk1jfXdHQSRyizOFX0lVU9PHCPoJPKFJzDVfpkyDY37fhs1yla1cUWE/wP75jIF5QtjfcYFWcHSvXliqmEFBfywCTBoGEhKUDf0Wk=,iv:yYibGKPZQiP+DJNFAM57X09ObBsESDM2mZyCCKxW2yY=,tag:XzjUHxpz5iiUyXoocxMeQQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h440ezlz0n2wf57mvdzfes8hglf7p543ryggjwgywlwlrwlmhczs4qtdzz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByMW1PN1JkRG8xRlFKdG90
            K3QraGxLVUFaclJXaHY3d3ZCWFhWeDV6emwwCmlKZkVlSkxDRWcvSWRUVFY5NEp1
            WG9sTWNzNi9xUlREZWlJRlFrRlQ4cjgKLS0tIDF6WVVUZFpML21Yd3BDYlJXWERu
            cjhldGR6MkViSTJ1eEkvTmx5ZTBpdzgKtj4y5WS+x35+vTB7iZWnMDL8Qq9SPxl8
            LjYuOxKnKkElYHIpvNn79UivahlCopUW0eUnLS4J86WI+LcAXhHp7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-03T22:38:09Z"
    mac: ENC[AES256_GCM,data:+PW2xAXFp4n63Sg9gL+9dgQgiwY0WZVaToDZmq2f99oy4gTVPR5dnj8KsvgQv2ES268pP42h6vqR2llaQV6sROXOsr0dbknvC/D2m7dJg/CtfqKHWNxo/BCXosafFtwUOl5MjHeesrTeQ51RiGA2O3ca0TpS2QchRx7AQnY/mDM=,iv:/eBpGDBVUIBglWGK0W6bpky47i8/xmSrq4F2fyoz9NA=,tag:YV4UV7s7PMOykoiakib0+g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
