apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-credentials
    namespace: infra
    annotations:
        sops.kubernetes.io/encrypted: "true"
type: Opaque
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:45S84FSWC/lAL5rmcHvi+22++wYd0b6fHW5vwQ0u6oitZCha,iv:gSAA57ZAykho/HJdMngQPzoRxooI79hqR6KdV9W6KRY=,tag:SmzE7vbjX5Q8MGX0dGdWiw==,type:str]
    credentials.json: ENC[AES256_GCM,data:SnEhlKCBTIJLKRtL+mihSSohx0+qPnlbo7mldghU2f9MAXQq1RrKp4yB/T36FdS1gAnqokshHN1f/Ed54xsMYDTXuS3DlfsjV9fwnaRLEVCAliqPbK6BcsuHGSplWEfPW3QGxRdW3nMZ2MW1nbyqL/8GZHp2iRhVcXlI1FNUwha4iCfMCtaQZ7vfTYZsIbh3mCz8CEqo9Ml8hbPw2uV+y5NAW5UeQxpRs3Cxxq6rlCZDOIU=,iv:pkRfWsskcSMpS6hsEZeTW+tyffDPyfy+5myb2MyZmGY=,tag:Qs7kF86OH17l0HGyKRQmhA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h440ezlz0n2wf57mvdzfes8hglf7p543ryggjwgywlwlrwlmhczs4qtdzz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyY2VoSUtRR0ZsWklwTGdN
            dWNIcXFLdEZsSTdLTXk5SyszWmZER3FHaHpVCmNwNVc3R0Qrd1hwY0d3QUw0OGxj
            QzlIVFRIWW5NQWVSMjExZlhQcWw0K28KLS0tIGpYcWxDTFBPOUt3Rmp3SGhSTmFp
            ZWcrUkY1d3FZWjlxa3g3bTlFRFZoT1UK1tt76cvQ8W2fVavtSqKjbLS4+wO1r5WQ
            2urjyiw7HmhrAAwKzaJAQvJPAUlE98cMmy7nTMVb8HGvENWLa6fZxQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-03T23:25:26Z"
    mac: ENC[AES256_GCM,data:xaJk2wsp/Po3a2iupeCLA0Ee1/x4YfEXNGa1kIOxuo8W/95wnacju4ezvizYFs+GxBctqKwa244B1lmJQqXV0ZxNUEOL1y6wIkUEzTUJ2vNli4BI8H+U532s0NUuh2e8kO0YHTuNio4Dwn7GW5chluRMEDrTYyOf4I7HYX58cBM=,iv:IMcH7t/XIvmeggRFdNgnv9YT6+GNZYO2mDuTVGSAL8s=,tag:vTUIBDoOXZhY++UJmgnPOQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
