apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    namespace: infra
stringData:
    PASSWORD: ENC[AES256_GCM,data:QGPQlULD1wBiI6JG,iv:hYzejCQkVsQY2rhgMyH2DkB/h4Hlx7fqV8lGQTlB+Bc=,tag:RoeZMqiYjVq52pnmtdw8+Q==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:gQcLctg8nCu5ZKIY,iv:VFR6O4ed3biy7bwiHllP5a/HNoSKLWbPBjk1LcGsaY8=,tag:DYFCSxdG9xFHVw7Om+QTzg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h440ezlz0n2wf57mvdzfes8hglf7p543ryggjwgywlwlrwlmhczs4qtdzz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWZkwwTUNRTEl6ZjVHR3p2
            bnRaeVFoamdYYTBRaUUxOWM5blRoMHAvczBJClNTUEhqTjFFOWppMW0rTFROeXlV
            d0ZyeUUway9KRmpVYVRSRnE3T2FnWW8KLS0tIC9XZ2dCS3pieGlaSmdCTEV2T0M4
            Ukk5NXRTc3lOWEp3cDU4YTU3YUY4bHcK30zebgcBbX5jvwmYomKVDJgvED7DJeP3
            pfZShLBpaqlQCtMKd/Ovibyr3pgn0o8uV5pNKVXzEaZQv611YtWZKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-19T16:21:07Z"
    mac: ENC[AES256_GCM,data:1W3JQ84G3Ph9Tov7f7WO0aZArJ9u5QjPvfE+w8cjlhaH7xPHBPyYrdFVW/CsGZcHRs2o20/89ZC09TR8wlSO8RcsEdsfJn5T+ol6WNqFKVYaSgSWHdnq2uWp+aMG1UBAeMaZNgBVPyPefepiLipV3yEkpzkMzhiOpRE7U6PjntE=,iv:mNwCE3/I9GHKwnnCNxewMaHbxVUlvfJ3qhJsuEO8Afw=,tag:4MmT6d48Pl7hL9vmvY/b0A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
