apiVersion: v1
kind: Service
metadata:
  name: amp-service
  namespace: infra
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  clusterIP: None 
---
apiVersion: v1
kind: Endpoints
metadata:
  name: amp-service
  namespace: infra
subsets:
- addresses:
  - ip: 10.0.10.3
  ports:
  - port: 8080
    protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: amp-ingress
  namespace: infra
spec:
  ingressClassName: nginx
  rules:
  - host: amp.jenya.lol
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: amp-service
            port:
              number: 8080
  tls:
  - hosts:
    - amp.jenya.lol
    secretName: jenya.lol
