apiVersion: v1
kind: Service
metadata:
  name: proxmox-service
  namespace: infra
spec:
  ports:
  - port: 8006
    targetPort: 8006
    protocol: TCP
  clusterIP: None 
---
apiVersion: v1
kind: Endpoints
metadata:
  name: proxmox-service
  namespace: infra
subsets:
- addresses:
  - ip: 10.0.10.2
  ports:
  - port: 8006
    protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: proxmox-ingress
  namespace: infra
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/ssl-verify: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx
  rules:
  - host: proxmox.jenya.lol
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: proxmox-service
            port:
              number: 8006
  tls:
  - hosts:
    - proxmox.jenya.lol
    secretName: jenya.lol
