apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  # - ../base/podinfo
  - ../base/technitium
  # - ../base/arc
  # - ../base/media
  # - ../base/pgadmin
  # - ../base/home-assistant
  - ../base/whoami
  # - ../base/odoo
  - ../base/changedetection
  - ../base/netboot
