apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  # - ../base/podinfo
  - ../base/arc
  - ../base/media
  - ../base/jenkins
  - ../base/pgadmin
  - ../base/orchard-bot
