apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-secret
    namespace: infra
data:
    cloudflare-key: ENC[AES256_GCM,data:DxBDEpodJ7xI4yWU0ecYCzGsZKzzsXIRN9Aj/GpO+VS1TE4A2FGeng==,iv:NtgYmObtRNo1T/rBU9mHA8RcL625K7z9jo3iCRNr844=,tag:9QbqFk60proeFgiSc1gkFg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h440ezlz0n2wf57mvdzfes8hglf7p543ryggjwgywlwlrwlmhczs4qtdzz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnQ3JGYnJ5bWRQRkxUK1FP
            dUlBZWZhbWNDZEcrQytPZmxEM3YvRmo5Y1RrClF5Q2x3QjFlQnZBdG8yb3NoU0la
            RDc4WFFCSFNZbTYxMXBKdm1iZUZGMGMKLS0tIFZJMmFSRmNLTjRyUVAweTRzUmYw
            TWNJakxkUkdockRGeS9RV3BoUmRJblEK0kUo1XDaxFUcQcv9uW9LdYL9QhOpcOkM
            jbfRqslOOZfqJy2WczWMS2Z980GyEdo/ocaGKrxF1kN25PdZo4kDrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-17T21:44:30Z"
    mac: ENC[AES256_GCM,data:bkjj+P+38v+m+yPCqrbqdeo7tf3D4bi4EU7baKUapJ/2dwJpa8rZGhKBOP6QmIXldMVuwTt1zjwEvGttse2/YZur7FOIPpejTNRV7Ty//dwUmF7xOEvij4ZO5eAohM1cGuATxzLxXqOj35DlVpVw9sEluUTr1N3dxu4jWRGGWaE=,iv:853PmKAXiM20UaQU6vYI0LkoWDC61G/0Pni7jmpl51A=,tag:FiiuCc5igd1x5prD7vKURA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
