apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-secret
    namespace: infra
data:
    cloudflare-key: ENC[AES256_GCM,data:5vFJbJBAIN5T1CkbVZR8bBKsG78sfhVHfI5mfWbtwUfuLMqhuoSI0g==,iv:KOY76cH0p/ELFvsWA1rGSo0NwT9CMae6QnYoh03qR+g=,tag:XwKxiYF6qXn1/ruFUePMQw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h440ezlz0n2wf57mvdzfes8hglf7p543ryggjwgywlwlrwlmhczs4qtdzz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsN0xWLyt2UDBrcDBvL0cr
            Nkkwc0duazdPVlppV0ErUEhjZHFXVHlMNkNjCm5DTFhOTCt1VmpvOWVMRHBJWUNP
            aUJDaUtQUGpSaXFDV3B4RjQvQXdRYUkKLS0tIGJmOWFyanBQZnJaaEM3RURtMkxG
            ckFETGNJeFBBUmJ0OC95Q3B6UkNSdGcK0iBkb6P3ni5yl3Bek3aWb+Ccf4E7r6Cb
            GgePBWtfottM4Sm8StvYLsfXhedRqDTIcxmyC46cO4FwLW/3m+4RQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-17T21:42:28Z"
    mac: ENC[AES256_GCM,data:PYnWRYSyTfuyZUtEnQCnnwnE8x58FT7RvvsimuvL+zi8kzQzw7OrLwhuWlrt10CQ3FfEb8hK8Dt6xeAU9xpn8HaOlGePYvnU4YYVrwuOcn7AWg490PGisXEIh+4T0uXDDBFCs3BbvsYZJ+aC7f1o2XVnn7mX0mUsDmnMdqWRHco=,iv:/5krxgbYR4bwTegF6SQ+hFPxScm68IvVjjc3RbV5T7c=,tag:Bgyh4P0INrmq0FBhz1phmQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
