apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-secret
    namespace: infra
stringData:
    cloudflareKey: ENC[AES256_GCM,data:JurTiQ90xXVdqaiZL6OYwF6VY03Htqxk3iqg7egtGVFaAirQpe1ltw==,iv:wb4yPRfM1K2bpn3wa8jlDRocjBHwyfXbUz5vkZ5Wg14=,tag:hM7+USwN9YpYrHtmyFNnHA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h440ezlz0n2wf57mvdzfes8hglf7p543ryggjwgywlwlrwlmhczs4qtdzz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPaERJOWhRRzZiNXgwYUlO
            aWVRNDk5eW5CNU4yWWdTNDk2RXFXdUZybGh3CmVGVFBmSkNlOWlSME12dy9ROHNi
            OXdscnNlZDcwV2VvaitIc2daNjltczAKLS0tIHEyTVdMOFdvemxVekRLL3k2Q0Za
            UkNoWlF2V0NNQUIyM0U3SllYNWhuNWcKIN5HUmqpZ8Sqs5ixbGRFlU54Mure8N3n
            rpG+OvV0WhKdLfvNej/qtqN9NfNXlpPX4kuOhcjndgvvTlze+POE5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-20T19:11:04Z"
    mac: ENC[AES256_GCM,data:LTJES+4lX2hMKfYXmqslHnjNrz3/5VkomecjvJDCQYko5/CSygF0YAvPkQigvDprIczSF5N4MOuzozDFWfKqKMzY/hIBz1LkTQ2DQ4tx2NcBiySw5BB3+e9KPbIwqMvClkYu7saA5qa6koOuJ3eAAUTy6ZSQvMLAbTny73vpQX4=,iv:qgMw1I9qdNC0BtnH+Zq9ZfBy/t+5Fk5GLqfnIl9umF4=,tag:lzrC6WddeXyZZY5oPnwd6w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
