apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-dev-wcard
  namespace: infra
spec:
  acme:
    email: me@jenya.lol
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-dev-wcard-private
    solvers:
      - dns01:
          cloudflare:
            email: me@jenya.lol
            apiKeySecretRef:
              name: cloudflare-secret
              key: cloudflare-key
