apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-secret
    namespace: apps
type: Opaque
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:HrguNIruV44YQM+yuT5qA4JqKcrQBRe0z1EZOT7PHwgEBBQmt4Z9iURiZaU=,iv:/MgJh2CsO5RgQgmdgZnbuI9BPyrrqb0QN06WmOnGcPA=,tag:COfGG8X84BIqRaAB1trdlg==,type:str]
    WIREGUARD_PRESHARED_KEY: ENC[AES256_GCM,data:uOi/XwPZMpKwunYHWV7aGj2F8jGOW6UfX/bXYnQHGOFNG9MKY0fB+I6Kask=,iv:qx/gbbF8Zo23DNq60In9k3MiCINEsKKOhi1egZfCNU8=,tag:K9UR+ZuarT53ej3UE2KusQ==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:S39Mz4w6Of+v2BPuqoBghw==,iv:IKQSSSJNZM6KBHSYNU21cLi13CMT0QWVCiyd++IJtDA=,tag:436ABzVgh+D+wtqhXjnvjA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h440ezlz0n2wf57mvdzfes8hglf7p543ryggjwgywlwlrwlmhczs4qtdzz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOUFM3ZW5kaERvcXZxL0hj
            bWp3YXdHYnByVVUxalMwN3VOMzRsWElxcmtBCjZyclFYY1RZNFp5RzJUb05PczZs
            OXhVekdwY0hjZkJwdEkvOXdwWGEzcU0KLS0tIFg4cHNyVllXc1FmemVmOEMzSGpB
            NGp0bjNROElscUNZRlp4dytOc3hTTHcKMO2vB8sm3AM01Oe17fNM6z/RNDS05/MQ
            MPfYl/ChW0DO55VYi2+DNBU+pvEmrKRsgOszj4rQ4Fvm8f4XypE10Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T13:59:33Z"
    mac: ENC[AES256_GCM,data:P6UpjaYpnbxebvToyuTt0Ax+gdRMh0wmBjE8/I2Y3Z6KMxPCZuUhi69GsPwiv524xOmXwUVkMtl7KgTBJTGIdeB7VvbsBz/g/fPoncky+T4ZORVR8hJtNZ/ZzSNPehFnS3dcTaJ1OKO5unPYayBUhEscl2o59cTaHndJaK8G5+A=,iv:sRIoCTRmxh9Ls3FxDeiOTyNMYvaj6fYmdfEP63e7qvo=,tag:u9o01A2T+7t/3gFNfXX/Vg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
