apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: arc-controller
  namespace: apps
spec:
  interval: 30m
  chart:
    spec:
      chart: actions-runner-controller-charts/gha-runner-scale-set-controller
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: gh-actions
        namespace: apps
      interval: 12h
