apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pvc.yaml
  - jellyfin/
  - plex/
  - qbittorrent/
  - sabnzbd/
  - radarr/
  - sonarr/
  - prowlarr/
  - profilarr/
  - flaresolverr/
