apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-pv
  namespace: apps
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 4Ti
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data"
