apiVersion: v1
kind: Secret
metadata:
    name: rabbitmq-secret
    namespace: infra
stringData:
    rabbitPassword: ENC[AES256_GCM,data:aDu1JkK/m/wr2kBF,iv:H9qoAHh+g+0KZ7w3gj3XxNA4JfNjDlkGsIPsVyU4dkc=,tag:Bmd/tu5i4yPnQq4OmlSmfQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h440ezlz0n2wf57mvdzfes8hglf7p543ryggjwgywlwlrwlmhczs4qtdzz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1VEpqcS9qemNtenVFVjJy
            TzlTelptK21XZWNQck45YXBmOHBJaVpmcDJBCkZsYnIwNzN1bW1Icm10QkY2c29H
            SmY0WDF0VDRST3Irc2tmVU45Nmo2akEKLS0tIDdZVXVBVDNyTnBaeHB5ZjFxMHNZ
            VXRibzVNd21aU29tMW1GeWlxd252TGsKSXxgq2K+EXjablg7wGyRsOhinjLBsuFb
            WtSFvvGK5QleUleIYvmA+L8gx0JqRKHpohLdvE28Wuyj5NHEUl6v8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-19T13:01:09Z"
    mac: ENC[AES256_GCM,data:LbE0i8v/W4Uu9pFQVQCgHBth+uXP1NgT9qdWgdmQe95LeubSsVlmmv0EVr0UOQwMPpiiG0IzeUY4GVEOe7iWoOFReAvWUeN8jUwdTigAwgfGO31b0nlBG85fDEy80P5tNm7akp9QYdQ9P2WzpjEmpj9XwVMreLwgBJhxFsPnr8E=,iv:SyhcNfAi53juj42nZvo6vQQis9Ckw4Jg2gwijoP/W3c=,tag:as1KSigbCuRIOfWlwKOWOw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
