apiVersion: v1
kind: Secret
metadata:
    name: kubero-secrets
    namespace: infra
    annotations:
        sops.kubernetes.io/encrypted: "true"
type: Opaque
stringData:
    KUBERO_WEBHOOK_SECRET: ENC[AES256_GCM,data:Pj+12xx6oyOtgkvP6lb+KR9MguNKvU7oMyfHXXV2vjjiOZ5JwKoWcg==,iv:YZTbl8qv6A9dTvM1UKusIT/Xh+tjCigF70zhGxHnHdk=,tag:rwJgsi1JapQZEf+OO6kpVQ==,type:str]
    KUBERO_SESSION_KEY: ENC[AES256_GCM,data:49hOPvnleQEcf3PyQqlY0J62NWhl2ETOr3KWJMO4Yk45b/rQoQYN3Q==,iv:ZZIFZXgG0icgGUB+dAF/Jc+wDfKT8+JcCDITAxshyKc=,tag:0vq2expXg+hQ8usC1cTwJA==,type:str]
    GITHUB_PERSONAL_ACCESS_TOKEN: ENC[AES256_GCM,data:JJUDSqwI7BW2FHjGZhC8prQ1ObhafH6Y01BCLQD1gcrZSa6agPF6b+lU0rON2YJAXH0Fsgb301ojTWb6U7RQgYDyC3kRoqiPRUalIqhjXJONYy5P6/K5TelveNP5,iv:SC5Zl6BgYktoMJCPq4RChE/MW2+6jFqiK/w+nYwZURY=,tag:hyOBL61ED0PQZqjab0yndQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h440ezlz0n2wf57mvdzfes8hglf7p543ryggjwgywlwlrwlmhczs4qtdzz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxbGhPdnNVREUvcXFOdGds
            Q012cTdQQU1jbkY1VU5WOFFoUGIveTE2NDJ3CkErbVZ3L3NTK1d6blc3LzFBcCt4
            MlltVzBtcEdkYTJiQXBrTGFIbEFicGMKLS0tIFlNVVlxc2NjUnJ4eHdSRUZlZEVX
            Ym16K0YxOVVkTGRTMFdjME05T0VuYWMKC0LKVujSgFhEmAd4+WzGHSj8aGoH+1bM
            mosvgpNN2oTHaYbFUGcDG761WXBviyG6YnEvuw5srFGt71PKJkJ4SA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-08T12:11:18Z"
    mac: ENC[AES256_GCM,data:YCS05km1xloPYM6z162OW0cDp0m+jdxARBZ3dGI0JxGk9hpcPExh9PMUtu2cgnLAscOjkPkpAciBVOp/In5N0E85yPnVKYtcLLh88/MYIzMEIFB4+TfCLxPA+ElYW/nPj2Sd81TrFLmjWRzqyIYJV1PHtpb1mfxCLiHxR4dXRmY=,iv:gUBeR1efbdurDQm2J98isc8053vadQIiHVakUmKHVhM=,tag:FiqLcGtRg0fEPsHImEpd7w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
