apiVersion: v1
kind: Secret
metadata:
    name: kubero-secrets
    namespace: infra
    annotations:
        sops.kubernetes.io/encrypted: "true"
type: Opaque
stringData: ENC[AES256_GCM,data:VzL/Wuw7EUHNqUGo0Cuz7LRwHyQUE8CasBiJUpRF+Y6uNnFMxSDR93/k5SpXQxeQtNA+wZJaqEQnBANLq+t83AOC7VqxtLCo+EaaYMPMwETK0+quoQ26GNT/xJxLwKvncndfeVhQGFHEpEqFvMZAZrAItI6CPTFm010=,iv:SlON9rRGRVyFyiQ/gm26a2SM85ekltiqKhK1nUyZntI=,tag:zAUGV6y6lD03JwwOUL4mZQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h440ezlz0n2wf57mvdzfes8hglf7p543ryggjwgywlwlrwlmhczs4qtdzz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQTXYrL2RpVEdMWGdUYUVF
            ODJJMGtMbENrTlh3UWw0WDZxaC8zU0c1T2pFClVZVU5HSTF1ZmdObHdheGE1Y3RT
            ZURCc1FXTnNZOC9EbCtUMFV6ZjJjRTQKLS0tIDhWUzdEenpRSkhpTEEwenRQNUh0
            bmdwOGp5dFNkZEhIa3UwaUs1ejUyakUKdg8bz1jGHtz8JxAo+WbpD5FfcRNdKZGS
            vcSlZu8Y3U6x6O1bHizlIk1NrHU1r0e7L4FKgz/dUkPdCGRdvQDmZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-08T11:30:12Z"
    mac: ENC[AES256_GCM,data:CyPwzb1VkHsmeq58UgeZngwPyIcNA38GbTmksO/qE99MJIyZWhnTCN/cjbP6NbjjEXR3njp2KilfVrkLtFAdhSQKahNwx9uBWbGCGThJ8WPNvgH8UBOVLaQA+RlqhBLpyjDgkDR4RjCVNrw4XH4YsACzOFR0oWQ/Y/PNW/opglo=,iv:Uoec26KuGQYoaD4wiNtstnp7i583RyZZGD3cUpUIVEY=,tag:zTUv4Nn+OxE/YDxe0dbyVA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
