apiVersion: v1
kind: ConfigMap
metadata:
  name: vps-dns-record
  namespace: infra
  annotations:
    external-dns.alpha.kubernetes.io/hostname: vps.jenya.lol
    external-dns.alpha.kubernetes.io/target: 202.61.206.227
    external-dns.alpha.kubernetes.io/ttl: "300"
data:
  info: "DNS record for vps.jenya.lol"
