apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-config
  namespace: flux-system
data:
  CLUSTER_IP: "192.168.0.40"
  PIHOLE_DOMAIN: "192.168.0.3"

  BASE_DOMAIN: "jenya.lol"
  WAITLE_DOMAIN: "waitle.com"
