apiVersion: v1
kind: Secret
metadata:
    name: cluster-secret
    namespace: flux-system
data:
    personal-email: ENC[AES256_GCM,data:UKMRXQbkVBZ9O8Mdrx/0PlcKhuKbFQ==,iv:hGhuOelHSXE8eIdykVq2bsa1mtZf9hwF8QHVAaojU4k=,tag:/PEdpCynZwp2mGAPXXrgcg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h440ezlz0n2wf57mvdzfes8hglf7p543ryggjwgywlwlrwlmhczs4qtdzz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkeEk0dVU1Z3hXN281SGhn
            d1h0eHRxTzNESkRqZlBwdFphSGdaQUVYaFZFCk9WN3ZEckJOVjBhZ2o0QjNsVU0y
            aWhDVGJJYnZMWmF5d09lUnZBamxHVncKLS0tIGZOOElHVWkyRDcvaHl3VEFiK3ZE
            ZzRxZ2M4UkdGNXhRaU4vaWtTOUFoVVEKUSMCeMuLeBQEBRgP8auxXpVrEDKm2BXS
            4OCdL5HrK+GFcB1TJC9GSqlbf5mpDfLrOSd4p8YR5an7ZqiomzISrA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-17T21:31:01Z"
    mac: ENC[AES256_GCM,data:Gu9MnxXlRgymdGgXzLaWbUK8l8vUpPjsm76Jl6MxLhVvLd8AK7fm1/I9tMrXeVyMjomymS28GLNcHY4zIlH7rzcn9HmrpzycD8JDPK1hxGCDC5XX5j0hGy4Nzwf8b7CoPQ/sxBf0+1fLWZkVqEdK+x2Fvb8DcbxICagUTZLGNPU=,iv:dZz+LoA1QPVpviarZe5xqnl5XP6CUKNefLcUWwLwzsg=,tag:yjPz3cGwzrIOQZ24PPtKQQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
