apiVersion: v1
kind: Secret
metadata:
    name: cluster-secret
    namespace: flux-system
data:
    personalEmail: ENC[AES256_GCM,data:jbHRLcXDcHIctnbR++n1CZ+/gd2TDg==,iv:ait9Zg3dCRS3EyO+HKwpXhexP4JVPGqSB0OoCkZ99JY=,tag:Ejpq34SyAT/eVRI0S098eA==,type:str]
    cloudflareToken: ENC[AES256_GCM,data:LzZoo17a7rY63d7Ou5kQ6h9GXVEHQyoHnezPNASfbVlGQLMkh4+shA==,iv:rpwD7+zHc+uizCpJV+h1r/TfZbkLpRWzayIGIW7oCHM=,tag:0aFBiMR7zEBFqpeK2/b2nQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h440ezlz0n2wf57mvdzfes8hglf7p543ryggjwgywlwlrwlmhczs4qtdzz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKbHdaT1dLcG53QjNTTk5i
            aVg1c0hLZGJYbm9jR2dQZ25oLzhCaHFCaGc0Ck9WYmxqYUhqMWJRZEQ1ekNPR2tD
            L2pzOGtCenRDMEE1dXBUVGUwMUZTbjQKLS0tIGwvVkNGNVNHNlgyZGRGWnhISHVC
            OEhPanpGSUd5MFI5OUJ2eVlHOW9PbUEK+HV6zpk0/atBSOBEllFmMu4YtObGpPol
            eYkl0yo3tgcZPrPKQbgovKQ1wP4DARdj3Ctldp/2Q6deSTTXxZnGTQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-17T21:26:05Z"
    mac: ENC[AES256_GCM,data:Mkp3uqmgWv0R51xM9je5h5lsPRuAWooeAjPpX0d9X/bS5uf9eYXWqWMp7OrruLXTQ8WWqlqge5LMHs3HdF7IZp8JU5vBbV4TBIx6RShkJT1cvtCQa0diiGXT60WrFAu8IkBUaBUimIvHD+5zlPXy8zs+4zAM/Qq6Q1NjXgggfas=,iv:GJd46TjHlrlRELRLE8h7mJ3/N+XHDiuci2LSxo2djGE=,tag:+sXE9v7LQaBVPcsYzvGFCA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
