apiVersion: v1
kind: Secret
metadata:
    name: cluster-secret
    namespace: flux-system
stringData:
    personalEmail: ENC[AES256_GCM,data:xRF2BOwpbTlaCuSrcz9j4sXWzS5JXQ==,iv:PpFE8kbOotiZ9TWevLApuuKp/9nPGv/dIGBvPylNdJw=,tag:O/6WcXR829ocnlTAxdModg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h440ezlz0n2wf57mvdzfes8hglf7p543ryggjwgywlwlrwlmhczs4qtdzz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpMldMcVU1bWJOaDVzakZ6
            ZTlSOXF3Ri9HaXROSWMyNkdwZlF2NGgyeEQwCnhua0o3NXRhbFE0YjUyZFBrMFpG
            engvQks1SDZzTDFoUmlhSXhLSmVtWlkKLS0tIEhQaXlEdzhnbEJUK3AvQlNOLzli
            YTZHM2VEVm5EZkhWSVhFT1kzaXlsY0kKSh+C9SjDQNgvq7pPjpp0tWQ2WBKnI0xJ
            fob9E7ybtZp4IKsrCeztMY04dLk/M27EGV7tCXZPqghO4Rk+GJp7Fg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-17T21:48:05Z"
    mac: ENC[AES256_GCM,data:UbB4PjM0Cdqs6lyzjStRjDJytqWQBPs5O5r9Y1nBhQqQlxenjG2vs1pE/loL+FX44gOvRX7weFsMijtcO5wSj/PYlCrrycRiLDYUN8m/Tq/d87WF9Y/k5Y1UVC931hCHvVKS1I9PIaRdiA6+RTCPW3UjZn5TFFCDV7Iorga7L7w=,iv:zpYRPFeqEPhifEPqgaRSF3cOFc8g/gs7G4VkxgGvong=,tag:HsKRSsKUJS2CFVZy0zw2yg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
