apiVersion: v1
kind: Secret
metadata:
    name: registry-secret
    namespace: infra
stringData:
    registryHtpasswd: ENC[AES256_GCM,data:1PMz92d9mrbgmeeOvR6nFTgAMmveF4SF1J2CElBLUIvKG0lWE89oBlSyGDOxVpmprvteikz40v1FV4ODO5q/qhpc,iv:O/jr3t1HzvcM3+C4wOmwtKqnSHCTXhL/mwSHGTftNCA=,tag:qDmO/kyAfeLYi5dX9jsgfA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h440ezlz0n2wf57mvdzfes8hglf7p543ryggjwgywlwlrwlmhczs4qtdzz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCUXNDOHdmT0N4TlJTN3Z2
            QXRaeWE3QVhMdk9wWnhhbCt4bVI0cTg3VnkwCmdwTTd2dW5Zd2ZwWHlmcEVSYVRP
            MGhOS3hZanVFTTN1TjlzL2Z5SWZ4WmsKLS0tIEp5MUxXcjhqQ3lrMFdIc2lXa3dZ
            bGVSS3hVaHdYaSt5V2tjY1Y2WjZ5bW8KIXddiUejwlO1YhAnmqC0m2/OBOcBmb4c
            xworvyzsAUwIxOClqL+olCa08pivmIpn6lSfl/aq9tkg2RpObqii+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-18T00:38:25Z"
    mac: ENC[AES256_GCM,data:urMGOqPQmXQ/TBu3zwCxFP0KEJImEzsXpFOwUs0KYae8+yFflydK2FVUPCYksAK+zbIONObnCJR2RS1VuVwGLpD3kqAUtK0++6s4bJKwZ333660aAnalUqZzNVM2jmtT7fnfHqZKjGV5zR5+7tjiSTNYnb32NV9T7dHeELDsPvY=,iv:3TOI0AxgZVy5Vmh8qP7fBBCL41JXq5tXi6eP1W0Br3A=,tag:I9XbhANWfIsaSjDBqIzm3g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
