apiVersion: v1
kind: Secret
metadata:
    name: plex-secret
    namespace: apps
stringData:
    PLEX_CLAIM: ENC[AES256_GCM,data:dwIYcJxwkTOLsF1QRz7AYUR9/4gHZhEgAH8=,iv:89fhhURoaMBXBF3KmgqpCbsd1T1U+ehrpldN2OsjYn4=,tag:kd2WjSL+ASKWyJ2qOfdSwg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h440ezlz0n2wf57mvdzfes8hglf7p543ryggjwgywlwlrwlmhczs4qtdzz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1NThhbGdhL0JFbTA5RTcx
            aDN1WDFJYUozUzB3UjNKdTVYZVcreEtqNEJjCjhXNDZhOG9wNEV3RzJ0NlUvNlU5
            T1AzcVFzUC9oNS9rTHgyRnMvSzFIQzQKLS0tIHB5WDFrb0lWcmkrWVg0bnptU3Qx
            dEw3UWdUdWkrQzMyWlZVMHJSOGR6YVkKPZ3qLgH1eJ7MSAw9oLG48vnFFIqrw++o
            om3cx4WLqKP+ZNfYQAHF34BHWBACScA5IhK1WzWSCdUWcXf0jfv/7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-05T21:54:31Z"
    mac: ENC[AES256_GCM,data:q7+UB++/MBhQLbMeVMM999rtLsEXHPfDg4yxRKXzBN73eZBmGc1RZkTUYrTAgV/w9k6iYLrMsMz+n817/5/h8mOa/WhCGOfMKMZjGPCZJj8o4g33ok+oKZTjB1mLJfEsPtEFHPT8U1FhkCLlQPf93odYZTCFNe9E3mPpkJMGmJc=,iv:Ph9RPDtSgivBejA9fDnss0kKMf4CUUkNVIjXpOPIGGo=,tag:InCyczWNWAOBksPKWb8gsQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
