apiVersion: v1
kind: Secret
metadata:
    name: plex-secret
    namespace: apps
stringData:
    PLEX_CLAIM: ENC[AES256_GCM,data:v8lCpjDlfjaKiKV5V/v9iJk3PMro52nmp1E=,iv:YMoJ2DxmlJNV/xyKfNBMXdv7HSN2NbM80Zb1gHaeZVs=,tag:almEbFJ1ib6mTT9faEnv3Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h440ezlz0n2wf57mvdzfes8hglf7p543ryggjwgywlwlrwlmhczs4qtdzz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5ZVhHOHR5ZW9uSnI5NnNB
            cHc2TURRUy93ZHNZcjBqaW5kSEptclpzYm1NCkFvNy8rY0xhYndQcDM5K0dzd1BH
            V2xIWGY1cHNsWW5iY3RWRFUybEFRb1EKLS0tIDJZSkcvLzdNVlZ0TDFBY1NkM1I1
            QlpPVGZWNXlINUtGOHUrSWQxTWZCVG8KFPSCw27997pI3BdKHqiYV6LF8BXlV6zF
            BbjlVtAvlbCXVg3uHAPfnqzuy3TGAQwOMe6USao3BHkxdz030Pv26Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-05T21:45:52Z"
    mac: ENC[AES256_GCM,data:Ipj0mSdi3n/5RStyivviIoDOkD2tgTCWdYXGK22/gHBh8KfKSeho06LLPo8ogCLy18fkuOBK7aDS0u+EVOQ911xHXaa+ZaW5OOAQl22aUdaWONfdgNshEY7O1P+ToyD9zs2L+zXsz0uuBDcDpOm91IkiVPQyWJC/RKhr4jf6nUE=,iv:ojCYB/Szk5tN0vMKiboRhxS2DJlg36zbno6DE0y7mvs=,tag:Dq9mix43NIhwwM+dFReoIw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
