apiVersion: v1
kind: Secret
metadata:
    name: plex-secret
    namespace: apps
stringData:
    PLEX_CLAIM_TOKEN: ENC[AES256_GCM,data:LwTzBR6DLMLj4IJzPEq2ZKgDnAhQk3ovPCg=,iv:+8BKhO2nKdr76g3NN/uJ2zKGMTY4tiz5NaPY9xn16xE=,tag:RGScDADOAMGFmkmtEFDFRA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h440ezlz0n2wf57mvdzfes8hglf7p543ryggjwgywlwlrwlmhczs4qtdzz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzUWRhL1Q5VWgrSmNVWEpa
            NEtJREhzdjczS2lRbDhwcEtRMDR2ZkpjS0EwCi9OYVZ6L1ZPZUJ5dmJCYk5CdkdN
            RFl1d3hIRE13aHJSNnJiYXpXVWpKazAKLS0tIHBmb3pZdmlINUR3cERrR2hMZzJF
            dHVieVZpZjNYVys3Sm9RQVdNS1pSYXMKUCzvQ0435eQ/U4WMBuv71PsbWLk0LVsS
            T4VcQK4kE9cobQufjBweJIF89D93A8GLGZB2EvazYnX0UPn3EYIX0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-05T22:03:45Z"
    mac: ENC[AES256_GCM,data:9LXXdQBpn/IMiGP71VHFTKO79qvvUXGmquSaS2U2uBRThhgg3N8YIWlVdwe+gEp36rfnd8y9d1LDIP8B2Xnu00DP8pdPxEy1B7NaY07Btuc6f02MLJf7czRE6D/tW69YX25SwxzLr5gQqXOptx5MIX7b13qmtO2yXjmXMx7fOJU=,iv:BLTv/75z3ReXUaMw+OHODVX+5rRZVgt3q41RjvrxwBQ=,tag:bOgHcny24uXfRhOBuQsQ0g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
