apiVersion: v1
kind: Secret
metadata:
    name: newt-credentials
    namespace: infra
    annotations:
        sops.kubernetes.io/encrypted: "true"
type: Opaque
stringData:
    PANGOLIN_ENDPOINT: ENC[AES256_GCM,data:xbeCjwGriunMOF5aGgu7nQCH80HIXUqt9wM=,iv:EAGG51OHSAcOjfO8xURInoKjXapM8wn52ihB670FNe4=,tag:w4b1u3S/9btI1gsTpm5CJw==,type:str]
    NEWT_ID: ENC[AES256_GCM,data:i932UX0ppexPQPmyJIV0,iv:N1GRKAoFGmACHoFvIUIIv+1wdQsbhpPsoJ/rXZyewCQ=,tag:2zzjaCQfH7noDBF+8wMPJQ==,type:str]
    NEWT_SECRET: ENC[AES256_GCM,data:66hWY5fIz56X9yVnKN7QRZDwslo7hUGBLJ7ipuxpHO55mYT0meOMpjW3Cs5/5fLw,iv:N2quB0FIvZFOZ0FPrnOVtXeOlTeTbKs8JQc3fN2s0Xg=,tag:3eXn9FwHLaeK6gP2uNGO/Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h440ezlz0n2wf57mvdzfes8hglf7p543ryggjwgywlwlrwlmhczs4qtdzz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxK0R6NWMxTVEyVVUyMG9p
            Q2taOGZFdEVFVy9NMVNKc1RSTEJPUS9idnpRCjJDaSthWjFtYkNlOENodDdkczFV
            NXdYZkw4L1NLRjA4ZFJsVmV2UUtBblkKLS0tIDIxdDB0d0h6T01ORitpKzVPcXdO
            YU9lcXNqLzBoM3ZpbzUrbmpXbTRjNlkKZEbBrGj/MVKj+huAapyZypxwjvRjr6rf
            yffIC9OWk93opreK95CnNeTLJ8txlYiBJxmvbV6EP1BZOOuaZ4hg9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-21T16:06:47Z"
    mac: ENC[AES256_GCM,data:zOVKHYDbSBbX1iU8380JpuCJOhNbiLkWhePbUW1crYPVvdIrY9lf229iLOCRAeZi0SrUuHZ9hFASq39op17VDX5TPGeyBk1l+L8i+Ts5VWwurmOuAufBNlu5VQPpFFYjy8Ptciabss7eV3Yu2rNzMM9RRjlbV+AbD6Slj7asIhE=,iv:91v4Js1EcWRgiZvuvPjihejJTnMEeTGV4/ECyF/fPUI=,tag:wEbCAlkKaxD+e0uGQh8W6w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
