apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: infra
spec:
  interval: 30m
  chart:
    spec:
      chart: ingress-nginx
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: infra
      interval: 12h
  values:
    controller:
      service:
        type: "LoadBalancer"
        electionID: ingress-controller-leader
        ingressClass: public-nginx # default: nginx
        ingressClassResource:
          name: public-nginx # default: nginx
          enabled: true
          default: false
          controllerValue: "k8s.io/internal-ingress-nginx"
      allowSnippetAnnotations: true
    admissionWebhooks:
      enabled: false
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx-public
  namespace: infra
spec:
  interval: 30m
  chart:
    spec:
      chart: ingress-nginx
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: infra
      interval: 12h
  values:
    controller:
      service:
        electionID: public-ingress-controller-leader
        ingressClass: public-nginx # default: nginx
        ingressClassResource:
          name: public-nginx # default: nginx
          enabled: true
          default: false
          controllerValue: "k8s.io/internal-ingress-nginx"
        annotations:
          tailscale.com/expose: "true"
      allowSnippetAnnotations: true
    admissionWebhooks:
      enabled: false
