apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-data-pvc
  namespace: apps
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Ti
  volumeName: data-pv
